### ISSUE TITLE
Add potential integration of local RAM, CPU and GPU usage  and print a table with the rightful metrics.

### ISSUE THREAD

**Issue by divital-coder** [divital-coder/Crochet-MultiModal-LLMs#3]
Loading image data along with prompts from the docvqa, over the gemini api for inferential outputs.
here we do not benchmark the model, since the api is essentially bridging the gap between GCP (google cloud platform) and your local device for input data, so in this context we will be benchmarking DOCVQA feasability with Gemini API.
hardware 
8 gigs ram
gtx 1650 
^do mention hardware resources as well

**Comment by HALAXAR** [comment]
will be exploring packages and then intergrating it with the new vision project
